name: sanchpethub
services:
  sanchpethub:
    container_name: sanchpethub
    image: floryn90/hugo:0.127.0-ext-debian
    command: server
    networks:
      - nginx-proxy-net
    volumes:
      - "./sanchpethub/:/src"
    restart: unless-stopped
    environment: 
      - VIRTUAL_HOST=${HUB_HOST}
      - LETSENCRYPT_HOST=${HUB_HOST}

networks:
    nginx-proxy-net:
        external: true
        name: ${PROXY_NET}
