services:

    nginx-reverse-proxy:
        image: "nginxproxy/nginx-proxy:latest"
        container_name: nginx-reverse-proxy
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        restart: always
        networks:
            - ${PROXY_NET}
        ports:
            - "80:80"
            - "443:443"
    letsencrypt:
        image: "nginxproxy/acme-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: nginx-reverse-proxy
            DEFAULT_EMAIL: ${LE_EMAIL}
        restart: always
        depends_on:
            - nginx-reverse-proxy
        networks:
            - ${PROXY_NET}

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  nginx-proxy-net:
    external: true
