name: links-website
services:
  links-website:
    container_name: links-website
    image: floryn90/hugo:0.127.0-ext-debian
    command: server
    networks:
      - nginx-proxy-net
    volumes:
      - "./links-website/:/src"
    restart: unless-stopped
    environment: 
      - VIRTUAL_HOST=${LINKS_HOST}
      - LETSENCRYPT_HOST=${LINKS_HOST}

networks:
    nginx-proxy-net:
        external: true
        name: ${PROXY_NET}
