baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Александр Петров (@sanchpet)"
  headline = "DevOps, студент. Работаю в хостинге. Пишу про технологии и личную эффективность."
  image = "img/avatar.jpg"  # path relative to static directory

  links = [
    { telegram = "https://t.me/sanchpet" },
    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    { github = "https://github.com/sanchpet" },
    { linkedin = "https://linkedin.com/in/sanchpet" },
    { mastodon = "https://techhub.social/@sanchpet" },
    { medium = "https://medium.com/@sanchpet" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

