name: sanchpetblog
services:
  sanchpetblog:
    container_name: sanchpetblog
    image: floryn90/hugo:0.127.0-ext-debian
    command: server
    networks:
      - nginx-proxy-net
    volumes:
      - "./sanchpetblog/:/src"
    restart: unless-stopped
    environment: 
      - VIRTUAL_HOST=${BLOG_HOST}
      - LETSENCRYPT_HOST=${BLOG_HOST}

networks:
    nginx-proxy-net:
        external: true
        name: ${PROXY_NET}
